### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by wezm** [wusyong/wusyong.github.io#1]
I'm interesting in following your progress on Verso and would like to subscribe to your blog in my RSS reader. It doesn't look like you have a feed though. It would be great if you could add one. The footer says you're using Zola, the docs on that are here: https://www.getzola.org/documentation/templates/feeds/ (mostly it's `generate_feeds = true` in `config.toml`).

**Comment by wusyong** [comment]
Thanks! I've updated and added the RSS icon on the home page.

**Comment by wezm** [comment]
Fantastic, thank you! I have subscribed.
